### ISSUE TITLE
Pull Request & Code Review 활용

### ISSUE THREAD

**Issue by bwmelon97** [cse-study/algorithm-code#3]
우리의 알고리즘 스터디의 목적 중 하나는 "**더 나은 코드를 작성하는 것**" 입니다.

알고리즘 문제를 푸는 것은 문제 해결 능력을 기르는 목적에는 충분히 부합하지만, 효율적인 코드 설계, 가독성 높은 코드 작성 등 "**좋은 코드**"를 만드는 능력을 기르는 데에 부족할 수 있다고 생각합니다. 그리고 저는 이 부분을 채워줄 수 있는 것이 **Code Review**라고 생각합니다. 더불어 자신이 생각한 방법과 다른 아이디어를 얻을 수 있고, 자신의 주언어가 아닌 코드를 보면서 다른 언어를 나중에 공부할 때 도움을 얻을 수도 있다고 생각합니다.

### 현재의 문제점

지금의 스터디 방식은 공동 문제를 선별한 후, 개별적으로 원하는 문제를 선택해 문제를 해결하는 코드를 작성해 `algorithm-code` 레포지토리에 바로 push해서 코드를 공유하는 형태로 진행되고 있습니다.\
이 방법은 code를 열람하는 데에는 문제가 없지만, 문제가 되는 부분은 **피드백을 주는 과정**에 있습니다. 현재 코드의 피드백을 작성하기 위해서는 issue를 open 해야 하며, code를 인용하여 피드백을 작성하는 것은 code에 직접 comment를 작성하는 것보다 가독성도 떨어지고 작성하기도 힘듭니다.\
반면에, **Pull Request의 Code Review** 기능을 활용하면, 문제별로 코드를 모아서 확인할 수 있을 뿐만 아니라, 코드 파일에 직접 comment를 작성해 피드백을 할 수 있습니다. 

 ### Pull Request의 Code Reivew 활용하기

제가 제안하는 코드의 공유 및 피드백 과정은 다음과 같습니다.

1. `cse-study/algorithm-code` 레포를 fork 하여, `개인계정/algorithm-code` 레포를 만듭니다.
2. `개인계정/algorithm-code` 레포의 로컬 레포에서 알고리즘 문제를 풉니다. (commit은 자유롭게 해도 됩니다.)
3. 로컬 레포에서 작성한 코드를 `개인계정/algorithm-code` 레포에 push 합니다.
4. `개인계정/algorithm-code` 에서 `cse-study/algorithm-code` 로 Pull Request 합니다.
   * Pull Request는 반드시 하나의 문제 단위로 보냅니다.
5. PR은 나머지 인원이 모두 code review를 한 후에 `cse-study/algorithm-code` 레포에 merge 합니다.
6. 새로운 문제를 풀기 전에 local repo를 rebase 해줍니다.
   ```bash
   $ git fetch upstream master
   $ git rebase upstream/master
   ```
7. 2번으로 돌아가 새로 문제를 풀면 됩니다.

5번에서 꼭 나머지 인원 모두의 코드 리뷰가 완료된 후에 merge할 필요가 있느냐는 의문이 들 수 있습니다. 제 생각으로는 저희 algorithm-study 레포는 코드를 공유하는 것이 주요한 목적이라 생각하기 때문에, 굳이 merge를 서두를 이유가 없다고 생각합니다. 만약 code review를 할 시간이 없다면, 나중에 시간적 여유가 생겼을 때까지 미뤄두었다가 해도 괜찮다고 생각합니다. 또한 좋은 점을 찾아서 언급해주는 것과 모르는 내용을 묻는 것도 피드백에 포함되기 때문에, 피드백을 너무 오래 붙잡고 있지 않아도 될 것이라고 생각합니다.

---

제 의견에 부족한 부분이 있거나, Pull Request 기능과 관련해 궁금한 점이 있다면 댓글을 남겨주세요 !\
혹은 제가 제시한 방법 외에 code review를 할 수 있는 방법이 있다고 공유 부탁드립니다 :)

**Comment by jiun0** [comment]
좋은 의견입니다. 다만 이는 스터디의 목적에 따라 달라질 사안이라고 생각합니다. 이전에도 리뷰에 관한 논의를 한 적이 있습니다. 요지는 '서로 다른 문제를 풀면 리뷰하기 힘드니 공동 문제를 정하자' 였습니다. 하지만 공동 문제를 정하는 것 자체가 시간이 걸리므로 원하는 문제를 푸는 것으로 결정했습니다. 리뷰가 제대로 이뤄지려면 다른 사람이 푼 문제에 대한 이해가 필요하므로 이 부분에 대해서도 생각해 볼 필요가 있을 듯 합니다. 

*참고로 저는 수근이 의견에 동의합니다. 그래서 전에 저런 이야기를 했던 거고요 ㅎㅎ 수근이 말대로 서두를 필요 없이 시간 되는 대로 자유롭게 의견을 교환하면 압박감을 느끼지는 않을 것 같습니다. 규율이 정해진 스터디도 얻는 것이 있지만 편하고 재밌게 하는 것이 더 오랫동안 즐겁게 할 수 있다고 보기 때문에 부담 가지지 않는 선으로 정하면 좋을 것 같습니다!

**Comment by yuhodots** [comment]
어.... 너무 좋은것 같아요! ㅋㅋㅋㅋㅋㅋ
부족한 부분 없고 추가하고 싶은 코멘트 없고 완벽한 것 같습니다 (귀찮아서 하는말 아님)

**Comment by yuhodots** [comment]
아 지운이의 말도 일리가 있네요 좀 더 고민해보겠습니다... ㅎㅎ 
오늘 내로는 생각정리해서 다시 답글 드리겠습니다~

**Comment by yuhodots** [comment]
PR은 모두에게 올리는 대신, 해당 문제를 한명도 풀지 않았을 경우가 존재하기도하고 시간 소요도 어느정도 걸리니 세명중에 한명만 approve해도 PR merge 하는 방식은 어떨까요?

**Comment by jiun0** [comment]
저도 그 방식이 나을 거 같아요. 지금 각자 쓰는 언어도 다 달라서 모든 사람이 의미 있는 PR을 할 수 있을까 싶기도 하고요.

**Comment by bwmelon97** [comment]
피드백을 하려던 중에 merge가 일어나거나, 하려고 생각했지만 당장 시간이 없어서 잠깐 미뤄둔 사이에 merge가 되는 상황도 생길 수 있으니,
피드백을 하지 않기를 원하는 경우에는 "확인했습니다" 정도의 코맨트를 남기거나 👍 이모티콘을 남기는 것 등을 통해 구분을 할 수 있으면 좋을 것 같습니다 !
그래서 3명이 모두 피드백을 마쳤거나 하지 않기로 했음을 확인하고 merge를 하면 어떨까 생각합니다

**Comment by bwmelon97** [comment]
추가로
> 1. `cse-study/algorithm-code` 레포를 fork 하여, `개인계정/algorithm-code` 레포를 만듭니다.

이 부분은 유호의 방법처럼 `cse-study/algorithm-code` 레포에 본인 이름의 branch를 만드는 것으로 대체해도 좋을 것 같습니다 !

**Comment by yuhodots** [comment]
> 피드백을 하려던 중에 merge가 일어나거나, 하려고 생각했지만 당장 시간이 없어서 잠깐 미뤄둔 사이에 merge가 되는 상황도 생길 수 있으니, 피드백을 하지 않기를 원하는 경우에는 "확인했습니다" 정도의 코맨트를 남기거나 👍 이모티콘을 남기는 것 등을 통해 구분을 할 수 있으면 좋을 것 같습니다 ! 그래서 3명이 모두 피드백을 마쳤거나 하지 않기로 했음을 확인하고 merge를 하면 어떨까 생각합니다

그러면 한명만 approve하면 merge하는 것은 아니고, 
'3명 모두 approve해야 merge할 수 있지만, 꼭 코드를 전부 이해하지는 않았어도 approve 가능하다' 정도로 여유를 두면 좋을 것 같습니다 :)

-> 위에 코멘트들은 모두 참고하고 정리해서 README에 추후 업데이트하도록 하겠습니다
